import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { AuthSessionProvider } from "@/components/providers/session-provider";
import { AppQueryProvider } from "@/components/providers/query-provider";
import { ThemeBootstrap } from "@/components/providers/theme-bootstrap";
import { NotificationProvider } from "@/components/notifications/notification-context";
import { ConfirmProvider } from "@/components/ui/confirm-dialog";
import { LiquidGlassPressProvider } from "@/components/motion/LiquidGlassPressProvider";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppQueryProvider>
          <AuthSessionProvider>
            <ThemeBootstrap>
              <NotificationProvider>
                <LiquidGlassPressProvider>
                  <ConfirmProvider>{children}</ConfirmProvider>
                </LiquidGlassPressProvider>
              </NotificationProvider>
            </ThemeBootstrap>
          </AuthSessionProvider>
        </AppQueryProvider>
      </body>
    </html>
  );
}
